const app=document.querySelector('#app'),connection=document.querySelector('#connection');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let session=null,state=null,selected=null,lastRound=-1,busy=false,polling=false,clockSync=0,lastServer=0;try{session=JSON.parse(sessionStorage.getItem('sensorSession'))}catch{};
async function api(action,b={}){const r=await fetch('https://microbit-sensor-quiz-1005.pariswing892.chatgpt.site/api/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,...b})});const d=await r.json();if(!r.ok)throw Error(d.error||'請稍後重試');return d}
function status(message,error=false){connection.textContent=message;connection.style.color=error?'#b43c38':'#61708a'}
function save(s){session=s;sessionStorage.setItem('sensorSession',JSON.stringify(s))}
function home(){app.innerHTML=`<div class="layout"><section class="panel"><div class="eyebrow">每組一部 iPad · 同步答題</div><h1>加入感應器挑戰賽</h1><p>向老師取得 6 位房間碼。小組一起討論，由一位同學提交答案。</p><label for="code">房間碼</label><input id="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="例如：123456"><label for="name">小組名稱</label><input id="name" maxlength="20" placeholder="例如：第 1 組"><div class="actions"><button id="join" onclick="join()">加入房間</button></div><p id="error" class="notice" hidden role="alert"></p></section><aside class="panel"><h2>👩‍🏫 老師主持</h2><p>建立房間後，將房間碼告訴各組。老師控制出題、暫停和揭曉。</p><button id="create" onclick="create()">建立新房間</button><p class="small">房間有效期為 24 小時。請使用小組名稱，無須輸入學生姓名。</p><a href="./local.html">使用共用電腦投影版</a></aside></div>`;status('')}
function error(e){const el=document.querySelector('#error');if(el){el.hidden=false;el.textContent=e.message}else status(e.message,true)}
async function create(){if(busy)return;busy=true;document.querySelector('#create').disabled=true;try{save(await api('create'));await refresh()}catch(e){error(e)}finally{busy=false;const b=document.querySelector('#create');if(b)b.disabled=false}}
async function join(){if(busy)return;let code=document.querySelector('#code').value.trim(),name=document.querySelector('#name').value.trim();if(!/^\d{6}$/.test(code)||!name)return error(Error('請填寫 6 位房間碼及小組名稱。'));busy=true;document.querySelector('#join').disabled=true;try{save(await api('join',{code,name}));await refresh()}catch(e){error(e)}finally{busy=false;const b=document.querySelector('#join');if(b)b.disabled=false}}
async function refresh(){if(!session||polling)return;polling=true;try{const d=await api('state');if(lastRound!==d.round){selected=null;lastRound=d.round}clockSync=performance.now();lastServer=d.now;const before=state;state=d;if(!before||JSON.stringify({...before,now:0})!==JSON.stringify({...d,now:0}))render();status('已連線 · 每秒更新')}catch(e){status(e.message+' · 正在重新連線…',true)}finally{polling=false}}
async function control(command){if(busy)return;busy=true;try{await api('control',{command});await refresh()}catch(e){error(e)}finally{busy=false}}
function pick(a){if(!state||state.phase!=='live'||state.paused||busy||mine())return;selected=a;render()}
function mine(){return state?.submissions.find(a=>a.team===state.myId)}
async function answer(){if(busy||selected===null)return;busy=true;render();try{await api('answer',{round:state.round,answer:selected});await refresh()}catch(e){error(e)}finally{busy=false;render()}}
function leave(){if(!confirm('離開此房間？未作答紀錄將保留。此裝置需重新加入另一房間。'))return;session=null;state=null;sessionStorage.removeItem('sensorSession');home()}
function elapsed(){if(!state?.started)return 0;return Math.max(0,((state.paused||lastServer+performance.now()-clockSync)-state.started-state.offset)/1000)}
function ranking(){let rank=1;return state.teams.map((t,i)=>{if(i&&(t.score!==state.teams[i-1].score||t.milliseconds!==state.teams[i-1].milliseconds))rank=i+1;return `<div class="rank"><div><strong>${rank===1?'🥇':rank+'.'} ${esc(t.name)}</strong><small>答對 ${t.correct} 題 · ${t.seconds.toFixed(1)} 秒</small></div><span class="score">${t.score}</span></div>`}).join('')}
function participants(){return `<div class="hostnames">${state.teams.map(t=>{let a=state.submissions.find(x=>x.team===t.id);return `<div class="chip"><strong>${esc(t.name)}</strong><div class="status">${a?state.phase==='review'?`${a.correct?'✅ +100':'💡 答錯'} · ${'ABCD'[a.answer]} · ${a.seconds.toFixed(1)} 秒`:`🔒 已提交 · ${a.seconds.toFixed(1)} 秒`:'等待作答'}</div></div>`}).join('')}</div>`}
function render(){if(!state)return;const host=state.host,s=state,q=s.question,m=mine();let body='';if(s.phase==='lobby'){body=host?`<div class="eyebrow">將房間碼告訴每組</div><div class="code">${s.code}</div><p>每組 iPad 開啟同一網站，輸入房間碼和小組名稱。</p><label for="link">學生入口（可貼到 Google Classroom）</label><input id="link" readonly value="${esc(new URL('./', location.href).href.replace(/\/$/,''))}"><div class="actions"><button class="secondary" onclick="copyLink()">複製學生入口</button></div><h2 style="margin-top:25px">已加入 ${s.teams.length} / 8 組</h2>${participants()}<div class="actions"><button onclick="control('begin')" ${s.teams.length<2?'disabled':''}>所有小組到齊，準備開始</button></div>`:`<div class="waiting"><div class="win">🙌</div><h1>${esc(s.name)}，加入成功！</h1><p>等待老師開始。和組員準備一起討論吧！</p></div>`}else if(s.phase==='ready'){body=`<div class="waiting"><div class="eyebrow">第 ${s.round+1} / 12 題</div><h1>準備下一個挑戰！</h1><p>題目會在老師開始計時後顯示。</p>${host?'<button onclick="control(\'start\')">▶ 顯示題目並開始計時</button>':'<div class="win">⚡</div>'}</div>`}else if(s.phase==='done'){body=`<div class="win">🏆</div><h1>挑戰完成！</h1><p>為每組的合作和努力鼓掌！</p>${ranking()}${host?'<div class="actions"><button onclick="download()">下載答題紀錄 CSV</button></div>':''}`}else{body=`<div class="topline"><div class="eyebrow">第 ${s.round+1} / 12 題 · ${esc(q.title)}</div><div class="clock" id="clock">${elapsed().toFixed(1)} 秒</div></div><h1>${esc(q.text)}</h1><div class="options">${q.options.map((o,i)=>host||s.phase==='review'?`<div class="option" ${s.phase==='review'&&i===q.answer?'style="background:#dcf8e6;border-color:#2c9e62"':''}><span class="letter">${'ABCD'[i]}</span>${esc(o)}</div>`:`<button class="answer-button ${selected===i?'selected':''}" onclick="pick(${i})" ${s.paused||m||busy?'disabled':''}>${'ABCD'[i]} · ${esc(o)}</button>`).join('')}</div>`;if(s.phase==='review')body+=`<div class="explain" role="status">✅ 正確答案：${'ABCD'[q.answer]}<br>${esc(q.explain)}</div>${host?participants():`<p>${m?m.correct?'🎉 答對了！獲得 100 分':'💡 下題一起再努力！':'這題未提交答案。'}${m?' 用時 '+m.seconds.toFixed(1)+' 秒':''}</p>`}${host?`<button onclick="control('next')">${s.round===11?'查看最終結果':'準備下一題'}</button>`:'<p>等待老師進入下一題。</p>'}`;else if(host)body+=`${participants()}<p>已提交 ${s.submissions.length} / ${s.teams.length} 組${s.submissions.length===s.teams.length?' · 全部到齊，可以揭曉！':''}</p><div class="actions"><button class="secondary" onclick="control('${s.paused?'resume':'pause'}')">${s.paused?'▶ 繼續計時':'⏸ 暫停計時'}</button><button onclick="reveal()">結束本題並揭曉</button></div>`;else body+=m?`<div class="explain" role="status">🔒 已提交 ${'ABCD'[m.answer]} · ${m.seconds.toFixed(1)} 秒<br>和組員一起等待老師揭曉。</div>`:`<p>${s.paused?'⏸ 老師已暫停計時。':selected===null?'請選擇一個答案，再按提交。':'已選擇 '+ 'ABCD'[selected]+'，和組員確認後提交。'}</p><button onclick="answer()" ${selected===null||s.paused||busy?'disabled':''}>${busy?'正在提交…':'確認並提交答案'}</button>`}
app.innerHTML=`<div class="layout"><section class="panel"><div class="roommeta">${host?'👩‍🏫 老師主持':'🙌 '+esc(s.name)} · 房間 ${s.code}</div><div style="margin-top:20px">${body}</div></section><aside class="panel" style="align-self:start"><h2>🏆 即時排行榜</h2>${ranking()}<p class="small">每題答對 100 分。同分比較答對題目的總用時。答案揭曉後才更新積分。</p><p class="small">用時以老師開始至伺服器收到答案計算，包含網絡傳送時間。請保持網絡連線。</p><button class="secondary" onclick="leave()">離開房間</button></aside></div>`}
function reveal(){if(state.submissions.length<state.teams.length&&!confirm('仍有小組未作答，現在揭曉？未答小組本題得 0 分。'))return;control('reveal')}
async function copyLink(){try{await navigator.clipboard.writeText(new URL('./', location.href).href.replace(/\/$/,''));status('已複製學生入口')}catch{document.querySelector('#link').select();status('請複製已選取的網址')}}
async function download(){try{let d=await api('export');let rows=[['題號','小組','答案','答對','答題秒數']];for(let r=0;r<12;r++)for(let t of state.teams){let a=d.rows.find(x=>x.round===r&&x.name===t.name);rows.push([r+1,t.name,a?'ABCD'[a.answer]:'未答',a?.correct?'是':'否',a?(a.milliseconds/1000).toFixed(3):''])}const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='microbit-小組答題紀錄.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){error(e)}}
function full(){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{})}
setInterval(refresh,1000);setInterval(()=>{let e=document.querySelector('#clock');if(e)e.textContent=elapsed().toFixed(1)+' 秒'},100);if(session)refresh();else home();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_quiz_standings',description:'Read the current room, question phase, and group scores.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(i){if(!i||Object.keys(i).length)throw Error('No parameters accepted');return state?{code:state.code,phase:state.phase,teams:state.teams}: {phase:'not_joined'}}})).catch(()=>{})}catch{}}
